### ISSUE TITLE
iOS app startup slow in debug

### ISSUE THREAD

**Issue by davidortinau** [dotnet/macios#22310]
### Description

When debugging iOS the app stalls for a long time on the splash screen. Android is significantly faster. I'm using defaults from a clean install on Ventura. VS Mac 17.4 stable, and .NET 7 GA.

https://user-images.githubusercontent.com/41873/202016900-e3cde432-18d2-4351-8703-3bc59728164e.mp4

### Steps to Reproduce

Run the CarouselViewDemos project from our samples. Update to 7.0.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/blob/main/6.0/UserInterface/Views/CarouselViewDemos/

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16

### Did you find any workaround?

nope

**Comment by rolfbjarne** [comment]
I'm going to close this issue, for a number of reasons:

* This issue is getting very long and unwieldy, and it's really hard to distill any meaningful information from it to try to diagnose any problems.
* An app being slow to debug can be due to _a lot_ of different issues. Some ours, some yours, sometimes maybe both. Having two separate problems in a single issue very quickly becomes confusing, and here there's many more than two separate problems.
* One issue has already been identified and addressed in Visual Studio ([how assemblies are loaded when the debugger attaches to the app](https://github.com/dotnet/macios/issues/22310#issuecomment-2701768692)).

This does _not_ mean we don't want to find and fix any problems you guys have, nor that we don't take any such problems seriously.

However, in order to best help you, please answer the following questionnaire as best as you can:

https://gist.github.com/rolfbjarne/72e051b78e59c7d48ed6b3b5e379e394

and then file a new issue, and we'll do our best to help you.

**Comment by nmg196** [comment]
OK but please close as "won't fix" not "completed".  Otherwise people will be mislead into thinking you've fixed it when we still have an unusable framework.

**Comment by rolfbjarne** [comment]
> OK but please close as "won't fix" not "completed". Otherwise people will be mislead into thinking you've fixed it when we still have an unusable framework.

GitHub doesn't really have a good option here, "won't fix" might make people think we don't want to fix this, which is certainly not the case either, but let's see how it goes.

**Comment by hopeko** [comment]
Ridiculous, still have this experience today on VS 17.14.12. It wastes dev time. 
"Some ours, some yours"? "Ridiculous, why never happen on Android.
After 3 months Maui cross-platform dev, today is the first day I start to seriously consider moving to Flutter. Too many bugs, waste of dev time. Maybe the only way to verify is to use a different solution.

**Comment by maexsp** [comment]
> Ridiculous, still have this experience today on VS 17.14.12. It wastes dev time. "Some ours, some yours"? "Ridiculous, why never happen on Android. After 3 months Maui cross-platform dev, today is the first day I start to seriously consider moving to Flutter. Too many bugs, waste of dev time. Maybe the only way to verify is to use a different solution.

Dont waste time with VS for iOS debugging. Use VS Code with cable connected phone/ipad or use Rider IDE. 
For us VS Code works best and stable! Rarely you may need to clear bin/obj folder, delete the app and delete all breakpoints for clean new debugging session.

**Comment by marcos-marimon** [comment]
Hi there,

Visual Studio 17.14.9, MAUI 9.0.110, and as a result, the same, the app is closed due to iOS launching deadline. Impossible to debug against a physical iOS device. More than 15 seconds loading assemblies before MauiProgram.CreateMauiApp() is called. It is incredible, but it worked like a charm with Xamarin Forms.

What a delusion with MAUI, everything works a lot worse, Android performance, iOS launching, and much more!!, As a result, hundreds or thousands of hours wasted trying to migrate, and keeping stuck on Xamarin Forms.

Thanks MAUI team!!

**Comment by bzd3y** [comment]
@marcos-marimon What an unnecessary, immature response. To be clear, I'm not on the MAUI team. And I've been just as frustrated as you. I just wasn't such a baby about it, at least not publicly, lol.

Did you try any of the steps outlined in this or other issues/threads to try to avoid this problem? There is a good chance that one of them will give you at least a temporary workaround.

My next suggestion would be to maybe grow up some and think about how likely it is for these guys to want to help you when you make comments like this.

**Comment by jonathanpeppers** [comment]
I would recommend trying out the new source generator for XAML, Stephane shows some numbers on it here:
* https://www.youtube.com/live/4EXGyCgVNp4?si=oFQBXbprOVd96HvC

It will be:
```xml
<ItemGroup>
  <MauiXaml Update="**/*.xaml" Inflator="SourceGen" />
</ItemGroup>
```
Or you can opt in/out on specific files using MSBuild.

When .NET 10 RC 2 releases, try it out. It should dramatically improve debug mode performance on all platforms (if you are using XAML).

**Comment by hopeko** [comment]
@jonathanpeppers I did try .NET 10 RC 1 & VS insider few days ago. Last time when I use .Net 9.0, I tried to debug on a remote iPhone connected to vmware on my windows to reduce startup duration, but it kept being interrupted due to timeout operation. It drove me crazy. And with .NET 10 RC 1 & VS insider, the problem fixed, though it still takes some minutes (sometimes close to 10 minutes to build and deploy on iOS), at least it works finally!!

The dramatic part is release publish's performance made a huge improvement, especially on iOS. Duration of Splash on both platforms are about 1 second. What an encouraging outcome. Though I don't know why it can't directly debug iOS on my windows, which it can using .NET 9.0 & VS 17. Now I have regained a little confidence in developing cross-platform apps using MAUI. Hope .NET 10 RC 2 will reduce deployment time for debugging on iOS, obviously, 10-minutes is not efficient programming.

**Comment by softlion** [comment]
@hopeko macos on vmware on Windows is not legal but also very very very slow. Use a Mac mini instead, even a refurbished one. it's less than 500$.

**Comment by hopeko** [comment]
@softlion I will, using macos on vmware on win is  just for experiment.
