### ISSUE TITLE
cannot build IOS after updating VS. MSBuild was unable to connect to the Mac. it IS connected to Mac?

### ISSUE THREAD

**Issue by exquirentibus** [dotnet/macios#23292]
### Apple platform

macOS, iOS

### Framework version

net9.0-*

### Affected platform version

VS 2022 to 17.14.8 preview 1.0 .NET SDK: Version:  9.0.302

### Description

I was able to build .NET9 Maui for IOS 2 days ago.  I upgraded VS 2022 to 17.14.8 preview 1.0 which updated .NET to 
.NET SDK: Version:  9.0.302
Host: Version:  9.0.7

Now,  I connect to Address='172.16.0.113' using Tools->IOS->Pair to Mac and have it show connected.  I select the tethered iPhone from IOS Remove devices.

And now when I clean and build in release mode, I get:
 
>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net9.0_18.5\18.5.9207\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(114,3): error : MSBuild was unable to connect to the Mac with Address='172.16.0.113' and User='xxxx'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists

### Steps to Reproduce

I've restarted both the MacStudio with Sequoia 15.5 and running latest Xcode 16.4 and my Windows 10 box.   No change. 

### Did you find any workaround?

No

### Build logs

even some of the log files have my full name so I must pass

**Comment by exquirentibus** [comment]
I also tried to build on VS 17.12.1 which also fails with the same exact error msg, so Visual Studio does Not seem to be the problem?

I tried putting global.json
{
  "sdk": {
    "version": "9.0.205"
  }
}
in the folder with my solution and dotnet --info confirms that VS is now using that version.

I rebooted the Mac, restarted VS.

However, VS 2022 17.14.8 preview 1.0 fails in exactly the same way?

I also tried VS 17.12.1, but Again ...

MSBuild was unable to connect to the Mac with Address='172.16.0.113' and User='xxx'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists

Going back to an earlier versions shouldn't be rocket science?  Are there other steps?

**Comment by exquirentibus** [comment]
I can ssh into the mac without issue from Windows.   ssh xxxx@172.16.0.113 (it created a new fingerprint) and asked me for my password.  Then I could see the mac in the dos prompt.

So I can pair and watch the progress as the .NET libraries etc. are all setup on the mac.

I can see my tethered iPhone in VS.

I can directly ssh into the Mac.

I can do .. Everything .. except .. BUILD?  And it worked fine before the VS upgrade which upgraded .NET9 also.

going back to the previous .NET with global.json doesn't get the build to work.  Build still complains about the connection?

This is Not making any sense?  How do I resolve this??

**Comment by rolfbjarne** [comment]
Please get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), this will contain a more detailed description of the failure.

**Comment by Felix-Dev** [comment]
We are seeing the same issue after updating VS from `17.13.4` to `17.14.8`. Building via the command line works when I manually move the Mac .NET SDK bits from ```/Users/{username}/Library/Caches/Xamarin/XMA/SDK``` to ```/Users/{username}/Library/Caches/maui/PairToMac/SDKs```.

**Comment by AurelienMGA38** [comment]
I've had the same error since upgrading VS to 17.14.8.
Opposite, I have a MAcBook Air in Sequoia 15.5 with XCode 16.4.

**Comment by exquirentibus** [comment]
> Please get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), this will contain a more detailed description of the failure.

after creating a new 'dev' user on my mac, going thu all the motions to create those logs (a Lot of steps to create new Mac account and get that setup with Xcode), I carefully read what the logs include.   Can't do it as my project files, etc.  include sensitive information.

I have generic setup.  Mac Studio with latest Sequoia 15.5   Windows 10-64 fully patched.  If you tell me specifically what you want from the logs, I can open them with the log viewer and give you that portion?

It failed exactly the same way when trying to build with that new dev account.  I can see my tethered iPhone from Windows VS 2022?

As I can pair, and also ssh, this is something .NET9 changed 2 days ago .. that affects Everyone, all versions of VS (I tried a much earlier untouched VS to test), and even when using a global.json to go Back to a previous .NET.

I only upgraded hoping that it would fix Sentry, which the Last .NET update killed for IOS.

So I'm stuck between a rock and a hard place and a bit frustrated as I have a bug in my IOS app that I .. Need .. to fix.

There really needs to be a simpler way to get useful logging info that does Not contain .. Everything .. as this is a public forum?

There should also be a way to roll back to a previous version (or possibly I'm unaware of the proper way)?

I can move back to .. Any .. Xcode version with ease?  Why can't I do that with VS and .NET?

Sorry to sound irritated but .. no doubt as you also are .. I'm stressed and behind on my work.

**Comment by MPoels** [comment]
I have the same problem, very frustrating, same issue need to fix the app, but can not build it!!
Wish I did not update VS2022 to 17.14.8 each time with an update I ran into issues with maui development. It takes more development time to produce a working environment again than the actual code changes take in the App. 

My error: 
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk.net9.0_18.5\18.5.9207\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(114,3): error : MSBuild was unable to connect to the Mac with Address='xx.xx.xx.xx' and User='xxxxxx'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists


I have no clue how to fix that, as the link with the apple machine, (after doing a lot of package updates) is established. And also reconnects well. Updating the packetstuff on the Apple machine has probably created the problem. But what a mess!

Frustrated user!

**Comment by exquirentibus** [comment]
@rolfbjarne

from the logs I created, maybe this is of use?  it created 6 nearly identical MSBuild_CommTrace_PID_20040.txt files.  I'm including from a few files here:

`OutOfProc Endpoint Packet Pump (TID 4) 638877591506608271 +    3.9054ms: Waiting for connection 900000 ms...
OutOfProc Endpoint Packet Pump (TID 4) 638877591506608271 +         0ms: Parent started connecting. Reading handshake from parent
OutOfProc Endpoint Packet Pump (TID 4) 638877591506608271 +         0ms: Building handshake for node type X64, NodeReuse, (version 1): options 16777228.
OutOfProc Endpoint Packet Pump (TID 4) 638877591506608271 +         0ms: Handshake salt is 
OutOfProc Endpoint Packet Pump (TID 4) 638877591506608271 +         0ms: Tools directory root is C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin
OutOfProc Endpoint Packet Pump (TID 4) 638877591506686414 +    7.8143ms: Successfully connected to parent.
OutOfProc Endpoint Packet Pump (TID 4) 638877591506725454 +     3.904ms: Changing link status from Inactive to Active
OutOfProc Endpoint Packet Pump (TID 4) 638877591506725454 +         0ms: Entering read loop.
 (TID 1) 638877591567158175 +  6043.272ms: Shutting down with reason: BuildCompleteReuse, and exception: .
OutOfProc Endpoint Packet Pump (TID 4) 638877591567353449 +   19.5274ms: Disconnecting voluntarily
OutOfProc Endpoint Packet Pump (TID 4) 638877591567353449 +         0ms: Changing link status from Active to Failed
OutOfProc Endpoint Packet Pump (TID 4) 638877591567353449 +         0ms: Ending read loop
 (TID 1) 638877591567353449 +         0ms: Changing link status from Failed to Inactive
 (TID 1) 638877591567978482 +   62.5033ms: Shut down complete.
 
  (TID 1) 638877595000084543 +         0ms: Shutting down with reason: ConnectionFailed, and exception: .
 (TID 1) 638877595000084543 +         0ms: Changing link status from Failed to Inactive
 (TID 1) 638877595000240776 +   15.6233ms: Shut down complete.

 
 
  (TID 1) 638877595000006396 +    3.9058ms: Attempting connect to PID 14264 with pipe MSBuild14264 with timeout 30 ms
 (TID 1) 638877595000006396 +         0ms: Writing handshake part 0 (16777228) to pipe MSBuild14264
 (TID 1) 638877595000006396 +         0ms: Writing handshake part 1 (1405299679) to pipe MSBuild14264
 (TID 1) 638877595000045449 +    3.9053ms: Writing handshake part 2 (17) to pipe MSBuild14264
 (TID 1) 638877595000045449 +         0ms: Writing handshake part 3 (14) to pipe MSBuild14264
 (TID 1) 638877595000045449 +         0ms: Writing handshake part 4 (14) to pipe MSBuild14264
 (TID 1) 638877595000045449 +         0ms: Writing handshake part 5 (31908) to pipe MSBuild14264
 (TID 1) 638877595000045449 +         0ms: Writing handshake part 6 (1) to pipe MSBuild14264
 (TID 1) 638877595000045449 +         0ms: Reading handshake from pipe MSBuild14264
 (TID 1) 638877595000084543 +    3.9094ms: Successfully connected to pipe MSBuild14264...!
 (TID 1) 638877595000084543 +         0ms: Shutting down node with pid = 14264
 (TID 1) 638877595000084543 +         0ms: MSBUILDNODEHANDSHAKESALT="", msbuildDirectory="C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin", enableNodeReuse=True, enableLowPriority=False
 (TID 1) 638877595000084543 +         0ms: Building handshake for node type X64, NodeReuse, (version 1): options 16777228.
 (TID 1) 638877595000084543 +         0ms: Handshake salt is 
 (TID 1) 638877595000084543 +         0ms: Tools directory root is C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin
 (TID 1) 638877595000123569 +    3.9026ms: Attempting connect to PID 20040 with pipe MSBuild20040 with timeout 30 ms
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 0 (16777228) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 1 (1405299679) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 2 (17) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 3 (14) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 4 (14) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 5 (31908) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Writing handshake part 6 (1) to pipe MSBuild20040
 (TID 1) 638877595000123569 +         0ms: Reading handshake from pipe MSBuild20040
 (TID 1) 638877595000162632 +    3.9063ms: Successfully connected to pipe MSBuild20040...!
 (TID 1) 638877595000162632 +         0ms: Shutting down node with pid = 20040
`

**Comment by TonyLugg** [comment]
Me too.  I can pair to the Mac but builds end in the error.  Mac OS 15.5.  VS 17.14.8

**Comment by Geir80** [comment]
I have the same problem. Updated from 17.13.4 to 17.14.8 and now I'm stuck.

**Comment by JORGEGO** [comment]
I have the same problem. Updated from 17.13.4 to 17.14.8 and now I'm stuck.

**Comment by rolfbjarne** [comment]
We're looking into this at the moment, hopefully we can come up with a workaround or fix asap.

In the meantime it might be possible to roll back to the previous version of Visual Studio: https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-rollback/

**Comment by exquirentibus** [comment]
> In the meantime it might be possible to roll back to the previous version of Visual Studio: https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-rollback/

I'm following a few threads on developercommunity.visualstudio.com on this issue.  I believe one of them mentioned he could build but not publish after rolling back as many changes had taken place on the Mac also?  Publishing is the whole point?

The only .. Certain success I've seen reported is using VS Code to build and publish from the Mac.  

I'm nervous about making changes as it's obvious a new .NET9 build will fix this (as older VS 2022 wouldn't connect after the .NET9 update).

I suppose I'll setup a completely separate windows & Mac pair and upgrade that first in the future (when this has been fixed lol) so I'll know whether to upgrade VS or .NET .. or to Wait!

**Comment by exquirentibus** [comment]
On https://developercommunity.visualstudio.com/t/After-Update-to-17148-Im-unable-to-bu/10934224#T-N10936185

Mauro Agnoletti from MSFT suggested:
run the following command in a command prompt: dotnet workload install ios --version 9.0.204

My AI is uncertain if that will work with the latest Xcode?

I'm showing these on my box now:
H:\>dotnet workload list
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    35.0.78/9.0.100        VS 17.14.36301.6
ios                        18.5.9207/9.0.100      VS 17.14.36301.6
maccatalyst                18.5.9207/9.0.100      VS 17.14.36301.6
maui-windows               9.0.51/9.0.100         VS 17.14.36301.6

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]
  9.0.108 [C:\Program Files\dotnet\sdk]
  9.0.205 [C:\Program Files\dotnet\sdk]
  9.0.302 [C:\Program Files\dotnet\sdk]

I'm unclear on how to relate 9.0.204 to my existing workloads?  And if I change something, then whatever the Real fix is might act differently on my machine?

But this workload install  sounds .. interesting?

**Comment by rolfbjarne** [comment]
> run the following command in a command prompt: dotnet workload install ios --version 9.0.204

That version number is a _workload set version_: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets

That maps to the iOS workload's version 18.4.9288 as can be seen in the json file in this NuGet: https://nuget.info/packages/Microsoft.NET.Workloads.9.0.200/9.204.0

Here's the release page for the iOS workload version 18.4.9288: https://github.com/dotnet/macios/releases/tag/dotnet-9.0.1xx-xcode16.3-9288 - this is the release for Xcode 16.3, which is _not_ the latest Xcode (which is Xcode 16.4). It's possible you'll have to install Xcode 16.3 if you install this workload set.

**Comment by exquirentibus** [comment]
> > run the following command in a command prompt: dotnet workload install ios --version 9.0.204
> 
> That version number is a _workload set version_: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets
> 
> That maps to the iOS workload's version 18.4.9288 as can be seen in the json file in this NuGet: https://nuget.info/packages/Microsoft.NET.Workloads.9.0.200/9.204.0
> 
> Here's the release page for the iOS workload version 18.4.9288: https://github.com/dotnet/macios/releases/tag/dotnet-9.0.1xx-xcode16.3-9288 - this is the release for Xcode 16.3, which is _not_ the latest Xcode (which is Xcode 16.4). It's possible you'll have to install Xcode 16.3 if you install this workload set.

https://github.com/XcodesOrg/xcodes should make that very easy to do!   My only concern is losing bug fixes in later .NET9 so this requires a lot of re-testing.

**Comment by exquirentibus** [comment]
I was successful in building for IOS after:
  
dotnet workload install ios --version 9.0.204
global.json:
{
  "sdk": {
    "version": "9.0.205",
    "rollForward": "latestPatch"
  }
}

I did Not have to downgrade Xcode.  

dotnet --info
.NET SDK:
 Version:           9.0.302
 Commit:            bb2550b9af
 Workload version:  9.0.204
 MSBuild version:   17.14.13+65391c53b

.NET workloads installed:
 [ios]
   Installation Source: SDK 9.0.300, VS 17.14.36301.6
   Manifest Version:    18.4.9288/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.ios\18.4.9288\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.7
  Architecture: x64
  Commit:       3c298d9f00

**Comment by twojnarowski** [comment]
I run this `dotnet workload install ios --version 9.0.204` command, and added the `global.json` file with:
```json
{
    "sdk": {
        "version": "9.0.205",
        "rollForward": "latestPatch"
    }
}
``` 
but it was causing this error: `There was an unhandled exception trying to get the iOS run session. Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.`
So I removed the `global.json` file and after that is suddenly started working again with iOS simulator.

**Comment by exquirentibus** [comment]
> I run this `dotnet workload install ios --version 9.0.204` command, and added the `global.json` file with:
> 
> {
>     "sdk": {
>         "version": "9.0.205",
>         "rollForward": "latestPatch"
>     }
> }
> 
> but it was causing this error: `There was an unhandled exception trying to get the iOS run session. Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.` So I removed the `global.json` file and after that is suddenly started working again with iOS simulator.

with dotnet --info I have these NET9 sdk installed, and you probably don't have 205?

.NET SDK:
 Version:           9.0.205
 Commit:            61baa8ef64
 Workload version:  9.0.204

.NET SDKs installed:
  9.0.100 [C:\Program Files\dotnet\sdk]
  9.0.108 [C:\Program Files\dotnet\sdk]
  9.0.205 [C:\Program Files\dotnet\sdk]
  9.0.302 [C:\Program Files\dotnet\sdk]

ideally, we'd want 9.0.302 but I think that's where the problem is happening.  205 maybe be 'better' or more stable that 204 which may be the version you are now using?

But, honestly - do I know what I'm doing?  No .. I'm mostly relying on a lot of different paid AI to fix this issue.

Hopefully someone from MS with more comprehension of what should be done will chime in?  I just needed to get a bug fix out for IOS so ...

**Comment by standamikes** [comment]
@rolfbjarne do you have any release date for that fix? None of the workarounds worked for us. Thank you

**Comment by malsabi** [comment]
I'm also having the same issue, I can pair to the mac but I cannot build on any simulator

**Comment by rolfbjarne** [comment]
> [@rolfbjarne](https://github.com/rolfbjarne) do you have any release date for that fix? None of the workarounds worked for us. Thank you

Did you try installing the previous version of the iOS workload like Mauro describes here: https://developercommunity.visualstudio.com/t/After-Update-to-17148-Im-unable-to-bu/10934224#T-N10936185

> While we work on fixing this for good, you can try installing a previous ios workload version to see if you can get unblocked. Please run the following command in a command prompt: "dotnet workload install ios --version 9.0.204"

**Comment by dannybeckett** [comment]
@rolfbjarne I already tried `dotnet workload install ios --version 9.0.204` but it did not help. My Mac is paired and connected. I still get this error:

> MSBuild was unable to connect to the Mac with Address=‘x’ and User=‘x’. This connection is separate from Visual Studio and without it the project can’t build. Please try building again or report this problem if the issue persists

If I try to run it again, I just get:

```
PS C:\Users\Me> dotnet workload install ios --version 9.0.204

Installing workload version 9.0.204.
Workload(s) 'ios' are already installed.

Successfully installed workload(s) .
```

**Comment by twojnarowski** [comment]
You can also try to remove everything in AppData/Local/TEMP folder and reboot your computer, then try again.

**Comment by exquirentibus** [comment]
I noticed a Very interesting post that seems to explain what is happening with the failure to connect issue:
https://developercommunity.visualstudio.com/t/After-Update-to-17148-Im-unable-to-bu/10934224#T-ND10936172

My Environment:

    Visual Studio Version: 17.14.8
    Mac OS: macOS & Xcode (latest updates)
    .NET MAUI 9
    Mac Account Full Name: “John Doe” (a placeholder name)
    Mac Account Username (Short Name): johndoe (no spaces, a placeholder name)

Problem:
When building, VS reports: MSBuild was unable to connect to the Mac with Address=‘192.168.1.25’ and User=‘John Doe’. (error message using the full name)

Root Cause Identified:
The core issue appears to be that MSBuild is trying to connect using my Mac’s “Full Name” (“John Doe”, as reported in the error message) as the SSH username, instead of the correct “Account Name” (johndoe, as confirmed in macOS Advanced Options).

Confirmation:
Manual SSH from Windows using ssh johndoe@192.168.1.25 works perfectly, confirming network and Mac SSH service are fine.
Manual SSH using ssh "John Doe"@192.168.1.25 fails (connection reset/closed).

This suggests VS/MSBuild is using the wrong username format internally.

Impact:
This bug severely impacts iOS build/publishing via “Pair to Mac”. This functionality was a critical workaround in previous VS versions (when direct iPhone connection was broken), highlighting a regression.

Please prioritize this fix.

pc

**Comment by dbSoft-SoftwareSolutions** [comment]
We have the same issue any workround?

**Comment by JORGEGO** [comment]
I've verified that the new version of Visual Studio is still experiencing this error. Can we get an approximate fix for this? Thank you very much.

**Comment by dannybeckett** [comment]
So far we have had a week of downtime. This is apparently normal for Microsoft when it comes to building MAUI projects to iOS. I have complained to them before on the Visual Studio developers forum, about the ludicrous levels of downtime when they break iOS builds. They do not care one little bit.

This isn't an isolated incident, they break iOS builds CONSTANTLY and for a prolonged period of time every time! The last time was when they made us make changes to the registry to fix a problem with their server being down, preventing local builds.

An enormous company like this seems to just be begging for a lawsuit for loss of earnings, similar to what the airlines did to CrowdStrike for the downtime they caused.

**Comment by MPoels** [comment]
I can confirm the new version did not solve the error as Danny already did. Same sad situation here....

**Comment by dbSoft-SoftwareSolutions** [comment]
> So far we have had a week of downtime. This is apparently normal for Microsoft when it comes to building MAUI projects to iOS. I have complained to them before on the Visual Studio developers forum, about the ludicrous levels of downtime when they break iOS builds. They do not care one little bit.
> 
> This isn't an isolated incident, they break iOS builds CONSTANTLY and for a prolonged period of time every time! The last time was when they made us make changes to the registry to fix a problem with their server being down, preventing local builds.
> 
> An enormous company like this seems to just be begging for a lawsuit for loss of earnings, similar to what the airlines did to CrowdStrike for the downtime they caused.

Problem is not the bugs... The real problem is that they make so long to fix critical bugs

**Comment by exquirentibus** [comment]
I think my post last nite points to the actual problem.  Here is a possible solution if anyone wants to mess with this?

**On Mac, create/edit `/etc/ssh/sshd_config`:**
```bash
# Add this section
Match User "John Doe"
    ForceCommand /bin/bash -c "exec /bin/bash"
    AuthorizedKeysFile /Users/johndoe/.ssh/authorized_keys
    PasswordAuthentication yes
```

**Then restart SSH:**
```bash
sudo launchctl stop com.openssh.sshd
sudo launchctl start com.openssh.sshd
```

## Testing the Solution

**Test both usernames work:**
```cmd
# From Windows
ssh johndoe@192.168.1.25        # Should work
ssh "John Doe"@192.168.1.25     # Should now work too

**Comment by nickpeppers** [comment]
> I think my post last nite points to the actual problem. Here is a possible solution if anyone wants to mess with this?
> 
> **On Mac, create/edit `/etc/ssh/sshd_config`:**
> 
> # Add this section
> Match User "John Doe"
>     ForceCommand /bin/bash -c "exec /bin/bash"
>     AuthorizedKeysFile /Users/johndoe/.ssh/authorized_keys
>     PasswordAuthentication yes
> **Then restart SSH:**
> 
> sudo launchctl stop com.openssh.sshd
> sudo launchctl start com.openssh.sshd
> ## Testing the Solution
> **Test both usernames work:**
> 
> # From Windows
> ssh johndoe@192.168.1.25        # Should work
> ssh "John Doe"@192.168.1.25     # Should now work too

Made the changes you recommended and was able to ssh using both usernames from Windows, but still getting the same error.

**Comment by exquirentibus** [comment]
Damn!  the original poster seemed to have solved it?

No use to me as I if I got the new version of IOS to work (I'm working now with the 204 workload), then I'd lose Sentry which won't build for IOS with new .NET?

Lately .. .NET has been like .. Whack-a-Mole lol??   As most of the development with Maui is for phones (I use it for multi-window Windows & phones, but that took a Lot of effort?) .. it seems odd that MS would put out all these versions that won't even .. Build?

**Comment by dbSoft-SoftwareSolutions** [comment]
> While we work on fixing this for good, you can try installing a previous ios workload version to see if you can get unblocked. Please run the following command in a command prompt: "dotnet workload install ios --version 9.0.204"

This work around worked for me!!

**Comment by Kanat9494** [comment]
I have the same problem

**Comment by Kanat9494** [comment]
It can work, if you downgrade your .net maui project from .net 9 to .net 8

**Comment by ThomasFOG** [comment]
Same boat. I need to ship a build now and nothing works anymore.

```dotnet workload install ios --version 9.0.204``` does not work, and we technically can't downgrade this app (downgrading to net8 makes it block on another bug that was fixed in later versions).

The state of .NET on mobile is really weird... and I don't understand why the Visual Studio components to debug a mobile app are hidden inside the MAUI VS workload. This is written nowhere and unintuitive for developers who don't make MAUI apps with Visual Studio (e.g. you might assume that the iOS and Android components are what you're looking for, but you actually _need_ the MAUI component for anything mobile to work).

**Comment by Kanat9494** [comment]
I could rebuild my .net maui project in vs with paired to mac, when downgraded maui project from .net 9 to .net 8

**Comment by ThomasFOG** [comment]
Can't downgrade here, we're bound to .NET 9. Also can't downgrade Visual Studio as we can only downgrade to previous install, not older.

Basically bound to waiting a month or so for the next service release to include the fix, missing a milestone delivery.

**Comment by Kanat9494** [comment]
Yes, it connected to mac and I didn't downgrade visual studio. I've updated Visual studio today and I've just cloned my app from github when it was still .net 8. i've updated my project to .net 9 yesterday and didn't commit it to github, so I still have my app in github with .net 8

**Comment by DanielJMHoffman** [comment]
This did work for me:

- Both windows & mac: run `dotnet workload install ios --version 9.0.204` command 
- Restart both mac & windows.
- Forget the mac connection & reconnect from scratch.

**Comment by ThomasFOG** [comment]
Forgetting the connection did the trick after ```dotnet workload install ios --version 9.0.204``` 👍

**Comment by lobbo232** [comment]
@dbSoft-SoftwareSolutions this was closed as "completed" but i'm still experiencing the issue on the latest VS build (17.14.9).

Could you provide some info on what the fix is/was and how we can get it?

**Comment by denhaandrei** [comment]
> Forgetting the connection did the trick after `dotnet workload install ios --version 9.0.204` 👍

not works for me, current issue resolve but require newer version to build

**Comment by ThomasFOG** [comment]
> [@dbSoft-SoftwareSolutions](https://github.com/dbSoft-SoftwareSolutions) this was closed as "completed" but i'm still experiencing the issue on the latest VS build (17.14.9).
> 
> Could you provide some info on what the fix is/was and how we can get it?

You'll have to wait for the next .NET 9 release that you can follow [here](https://github.com/dotnet/macios/releases). Assuming that the fix gets into the .NET 9 servicing and follows the typical release schedule, you might except it to release in about a month or so.

**Comment by denhaandrei** [comment]
These steps work for me:
Update to 17.14.9
Close all VS instances
Remove all files from %user%\%appdata%\%local%\Xamarin\MonoTouch
Pair again with Mac and rebuild the project
Install the latest SDK on Mac https://dotnet.microsoft.com/ru-ru/download/dotnet/9.0

**Comment by AurelienMGA38** [comment]
Here is my MAC pairing log.
Does anyone have any ideas?

[Logs Pair MAC.txt](https://github.com/user-attachments/files/21313526/Logs.Pair.MAC.txt)

**Comment by rodolfo-sousa** [comment]
What worked for me:
- Update VS to 17.14.9;
- "version": "9.0.205" on global.json;
- deleted bin/obj project directories ;
- executed "dotnet workload install ios --version 9.0.204";
- Had to update Xcode to 18.5 because of Mac OS updates (you may not need to this one);
- Restart/Connect Mac machine;

PS: This is one of the reasons I don't update VS too often... I will end up having problems deploying to iOS...

**Comment by Micwi** [comment]
@rodolfo-sousa  I can confirm this worked for me.

**Comment by wesProg23** [comment]
@rodolfo-sousa Xcode 18.5 doesn't exists, right?

**Comment by rodolfo-sousa** [comment]
> What worked for me:
> 
> * Update VS to 17.14.9;
> * "version": "9.0.205" on global.json;
> * deleted bin/obj project directories ;
> * executed "dotnet workload install ios --version 9.0.204";
> * Had to update Xcode to 18.5 because of Mac OS updates (you may not need to this one);
> * Restart/Connect Mac machine;
> 
> PS: This is one of the reasons I don't update VS too often... I will end up having problems deploying to iOS...

Correction: Xcode 18.4

**Comment by ThomasFOG** [comment]
FYI Visual Studio 17.14.10 has released but there was no .NET servicing this time around. So the fix to this issue is currently not published yet.

**Comment by TonyLugg** [comment]
The 17.14.10 release notes indicate the fix for MAUI iOS is included.  It worked for me after changing workload back to manifest config, and updating workloads to the latest.

**Comment by ThomasFOG** [comment]
> The 17.14.10 release notes indicate the fix for MAUI iOS is included. It worked for me after changing workload back to manifest config, and updating workloads to the latest.

That [doesn't seem like the same issue](https://developercommunity.visualstudio.com/t/NET-9-MAUI-:-The-NET-runtime-905-or-/10934616). This issue requires a .NET release, which didn't happen yet.

**Comment by rodolfo-sousa** [comment]
I had again to run:
`dotnet workload install ios --version 9.0.300`
after install the 17.14.10 update.

**Comment by TonyLugg** [comment]
@ThomasFOG 
Actually, the first item in the release notes for 17.14.10 is the same issue as this one, see https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes?tabs=GA#17.14.10.  I installed it, changed workload config back to manifest so that it would resume installing the latest released workloads, did a workload update to force it to install the latest, and the 300 workload now works, I can build and debug on a device again.

**Comment by VNGames** [comment]
Is there any workaround for Xamarin?

> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.Messaging.Build.targets(113,3): error : MSBuild was unable to connect to the Mac with Address='XXX.XXX.XXX.XXX' and User='XXX'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists

The log says:

> 2>  [xma][info]: An error occurred while trying to connect. Details: No details provided
2>  exception: An error occurred while validating the SSH keys: openssh key type: ecdsa-sha2-nistp521 is not supported (TaskId:178)

Pairing works and MAUI works but Xamarin doesn't build
